### ISSUE TITLE
Design the style of the migrant application

### ISSUE THREAD

**Issue by gioppoluca** [micado-eu/migrant_application#42]
We need to have the style guid for the application.

Considering the quasar framework we need to have the colour schema, the style of the various button (glossy, rounded and so on)

If needed we need the CSS

**Comment by gioppoluca** [comment]
@jakob-synyo have you some feedback on this?

I'd like to see something before the call of wednesday, thanks

**Comment by jakob-synyo** [comment]
@gioppoluca We already designed some prototypes for the migrant app and will discuss it today in an internal meeting. Afterwards I will start to "transfer" the prototypes to quasar and provide you the needed files.

**Comment by JowieXiang** [comment]
@jakob-synyo Hi Jakob. Just a small reminder: please use the[ latest version of the wireframes ](https://micado.hcu-hamburg.de/nextcloud/apps/drawio/118616)as reference for the prototypes, since they are being updated quite rapidly. And also, it is recomended to use [nextcloud ](https://micado.hcu-hamburg.de/nextcloud/apps/files/?dir=/02.%20Consortium/02.%20Work%20Packages/WP4/02.%20WP4%20work%20and%20exchange%20folder/product%20design)to host all work in-progress :)

**Comment by jakob-synyo** [comment]
@gioppoluca Hey Luca, could you eventually assign @Leo-Moertenhuber to this issue (maybe also to other relevant design issues) as he is doing the prototypes based on the wireframes.

**Comment by Leo-Moertenhuber** [comment]
@gioppoluca Hi Luca, I just clicked through all the tasks I was assigned to - I hope I can get to everything before the call tomorrow. I will set up the first draft for a style guide, where I put everything into consideration. A few designed prototypes of the wireframes, the icons and so on. My goal is to send the guide out tomorrow morning so everybody can check it before the call.

**Comment by gioppoluca** [comment]
@Leo-Moertenhuber thanks
